In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import io
import seaborn as sns
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge

In [2]:
data = np.loadtxt("alkan/ALKAN.BLD")


In [3]:
data

array([[ 2.,  1.,  0., ...,  2.,  1.,  1.],
       [ 2.,  0.,  2., ...,  5.,  2.,  1.],
       [ 2.,  0.,  2., ..., 10.,  4.,  2.],
       ...,
       [ 6.,  0.,  0., ..., 31., 13.,  2.],
       [ 6.,  0.,  0., ..., 32., 14.,  2.],
       [ 6.,  0.,  0., ..., 30., 12.,  2.]])

In [4]:
data.shape

(74, 210)

In [5]:
n = data.shape[0]
m = data.shape[1]

In [6]:
(n,m)

(74, 210)

In [7]:
l = []
word = 'A1 '
with open('alkan/set-str/ALKAN.SET') as file:
    for line in file:
        if (word in line):
            ape = float(line.split()[1])
            l.append(ape)

In [8]:
print("Num_features =", len(l))
for i in range(min(len(l), 10)):
    print("feature", i,"=", l[i])

Num_features = 74
feature 0 = -88.63
feature 1 = -42.07
feature 2 = -0.5
feature 3 = -11.73
feature 4 = 36.074
feature 5 = 27.852
feature 6 = 9.503
feature 7 = 68.74
feature 8 = 60.271
feature 9 = 63.282


In [9]:
y = np.array(l)
y.shape

(74,)

In [10]:
y

array([-88.63 , -42.07 ,  -0.5  , -11.73 ,  36.074,  27.852,   9.503,
        68.74 ,  60.271,  63.282,  49.741,  57.988,  98.427,  90.052,
        91.85 ,  93.475,  79.197,  89.784,  80.5  ,  86.064,  80.882,
       125.665, 117.647, 118.925, 117.709, 118.534, 106.84 , 115.607,
       109.429, 109.103, 111.969, 117.725, 115.65 , 118.259, 109.841,
        99.238, 114.76 , 113.467, 106.47 , 150.798, 143.26 , 144.18 ,
       142.48 , 143.   , 141.2  , 132.69 , 140.5  , 133.5  , 136.   ,
       135.21 , 137.3  , 140.6  , 136.   , 135.2  , 138.   , 133.8  ,
       140.6  , 140.4  , 133.6  , 126.54 , 124.084, 137.68 , 139.   ,
       131.34 , 130.648, 140.46 , 146.168, 133.83 , 142.   , 136.73 ,
       140.274, 133.016, 122.284, 141.551])

In [11]:
def R_rise_2 (Eps, y, y_mean):
    result1 = np.sum(Eps**2)
    result2 = np.sum((y-y.mean())**2)
    return 1 - result1 / result2


def Correlation(X, Y):
    X_mean = X.sum() / X.shape[0]
    Y_mean = Y.sum() / Y.shape[0]
    res = ((X) * (Y)).sum()
    res1 = (((X) ** 2)) 
    res2 = (((Y) ** 2)) 
    
    return  res / (((res1.sum() * res2.sum())) ** 0.5)

In [12]:
size_buf = 10
num_selections = 10
min_correlation = 0.95
#100
#15

In [13]:
model = Ridge(alpha=0.2)

In [14]:
y_mean = data.sum(axis = 1)
y_mean = y_mean / m
y_mean

array([0.09285714, 0.1907381 , 0.33778095, 0.31322381, 0.53822857,
       0.50626667, 0.46634762, 0.79669048, 0.74421905, 0.74644286,
       0.7040619 , 0.69749048, 1.11633333, 1.06962381, 1.06011905,
       1.02632381, 0.99708095, 0.99303333, 1.00302857, 0.9837381 ,
       0.93640952, 1.494     , 1.42669524, 1.41860952, 1.43021905,
       1.40549524, 1.36054762, 1.37269524, 1.3561    , 1.37696667,
       1.35222857, 1.3351619 , 1.32382381, 1.3034619 , 1.2579381 ,
       1.27928095, 1.27077619, 1.29133333, 1.18765238, 1.95123333,
       1.87832857, 1.85914286, 1.87329524, 1.82781905, 1.83665714,
       1.78150476, 1.79542857, 1.79074286, 1.78900476, 1.79551905,
       1.7769    , 1.77144762, 1.76990952, 1.77332857, 1.76851429,
       1.76265714, 1.73765238, 1.7309    , 1.70322857, 1.6973619 ,
       1.72905238, 1.70461429, 1.6983381 , 1.73022857, 1.69916667,
       1.66721429, 1.67419048, 1.63922857, 1.64113333, 1.67244286,
       1.5761619 , 1.60750476, 1.60711429, 1.60879524])

In [15]:
buf_r = np.array([0.0 for i in range(size_buf)])
buf_size_ar = np.array([0 for i in range(num_selections)])
iter_buf = 0

buf_numbers = np.array([[-1 for i in range(size_buf)] for k in range(num_selections)])
buf_numbers_1 = np.array([[-1 for i in range(size_buf)] for k in range(num_selections)])

buf = np.array([[[float(i) for i in range(size_buf)] for j in range(n)] for k in range(num_selections)])

X1 = np.array([[float(i) for i in range(1)] for j in range(n)])
X2 = np.array([[float(i) for i in range(2)] for j in range(n)])
buf.shape

(10, 74, 10)

In [16]:
%%time
for i in range(m):
    X1[:,0] = data[:,i]
    model.fit(X1, y)
    if iter_buf < size_buf:
        tmp = model.predict(X1)
        ar = np.array([])

        for j in range (iter_buf):
            t = Correlation (buf[0, :,j], tmp)
            ar = np.append (ar, t)
        #print(ar)
        if (iter_buf == 0) or (ar.max() < min_correlation):    
            buf_r[iter_buf] = R_rise_2(y - tmp, y, y_mean)
            buf_numbers[0, iter_buf] = i
            buf[0, :, iter_buf] = tmp[:]
            iter_buf += 1
            
    else:
        tmp = model.predict(X1)
        ind = buf_r.argmin()
        ar = np.array([])
        for j in range (buf.shape[2]):
            t = Correlation (buf[0, :,j], tmp)
            ar = np.append (ar, t)
        #print(ar)
        if (ar.max() < min_correlation) and (buf_r[ind] < R_rise_2(y - tmp, y, y_mean)): 
            buf_r[ind] = R_rise_2(y - tmp, y, y_mean)
            buf_numbers[0, ind] = i
            buf[0, :, ind] = tmp[:]
buf_numbers_1[0, :] = -2
print(buf_numbers_1, end="\n\n\n\n")
buf_size_ar[0] = iter_buf
print(buf_size_ar[0])

[[-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]



3
CPU times: user 83.9 ms, sys: 0 ns, total: 83.9 ms
Wall time: 85.1 ms


In [17]:
%%time
for k in range (1, num_selections):
    iter_buf = 0
    for i in range(buf_size_ar[k - 1]):
        for j in range(0, m):
            #print(data[:,i].shape)
            X2[:, 0] = buf[k - 1, :, i]
            X2[:, 1] = data[:, j]
            model.fit(X2, y)
            if iter_buf < size_buf:
                tmp = model.predict(X2)
                ar = np.array([])
            
                for j1 in range (iter_buf):
                    t = Correlation (buf[0, :,j1], tmp)
                    ar = np.append (ar, t)
                #print(j, ar)
                
                if (iter_buf == 0) or (ar.max() < min_correlation):
                    buf_r[iter_buf] = R_rise_2(y - tmp, y, y_mean)
                    buf_numbers[k, iter_buf] = j
                    #print("*******",i, j)
                    buf_numbers_1[k, iter_buf] = i
                    buf[k, :,iter_buf] = tmp[:]
                    iter_buf += 1

            else:
                tmp = model.predict(X2)
                ind = buf_r.argmin()
                ar = np.array([])
                for j1 in range (buf.shape[2]):
                    t = Correlation (buf[0, :,j1], tmp)
                    ar = np.append (ar, t)
                if (ar.max() < min_correlation) and (buf_r[ind] < R_rise_2(y - tmp, y, y_mean)):
                    buf_r[ind] = R_rise_2(y - tmp, y, y_mean)
                    buf_numbers[k, ind] = j
                    buf_numbers_1[k, ind] = i
                    buf[k, :, ind] = tmp[:]
    buf_size_ar[k] = iter_buf

    print("selection", k + 1, "from", num_selections)

selection 2 from 10
selection 3 from 10
selection 4 from 10
selection 5 from 10
selection 6 from 10
selection 7 from 10
selection 8 from 10
selection 9 from 10
selection 10 from 10
CPU times: user 2.29 s, sys: 0 ns, total: 2.29 s
Wall time: 2.3 s


In [18]:
buf_numbers

array([[  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [  0, 130, 188,  -1,  -1,  -1,  -1,  -1,  -1,  -1]])

In [19]:
buf_numbers_1

array([[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1]])

In [20]:
buf_size_ar

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [21]:
lis = []
for i in range(buf_size_ar[num_selections - 1]):
    lis.append([buf_numbers[num_selections - 1][i]])

In [22]:
for i in range(num_selections - 1, 0, -1):
    #print(i)
    for j in range(buf_size_ar[i - 1]):
        lis[j].append(buf_numbers[i - 1][buf_numbers_1[i,j]])



In [23]:

lis

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [130, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [188, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [24]:
for i in range(buf_size_ar[num_selections-1]):
    lis[i].sort()
    print(lis[i])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 130]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 188]


In [25]:
clf = Ridge(alpha=0.1)
X_train, X_test, y_train, y_test = train_test_split(data, y, train_size=0.6, test_size=0.4)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9953840156353246

In [26]:
for i in range(buf_size_ar[num_selections-1]):
    clf.fit(X_train[:,np.unique(lis[i])], y_train)
    print(clf.score(X_test[:,np.unique(lis[i])], y_test))

-0.028770042183227318
0.8578940835330285
0.9700973365705552


In [27]:
clf_Lin = LinearRegression()
clf_MGUA = LinearRegression()
res_MGUA = clf_MGUA.fit(X_train[:,np.unique(lis[2])], y_train)
res_Lin = clf_Lin.fit(X_train, y_train)

In [28]:
predict_MGUA = clf_MGUA.predict(X_test[:,np.unique(lis[2])])

In [29]:
predict_Lin = clf_Lin.predict(X_test)

In [30]:
for i in range(predict_Lin.shape[0]):
    print("МГУА", predict_MGUA[i], "Лин.регрессия", predict_Lin[i], "Истинное значение", y_test[i])

МГУА 142.24207734573667 Лин.регрессия 131.2301092041269 Истинное значение 132.69
МГУА 155.64235432346453 Лин.регрессия 148.338518110071 Истинное значение 150.798
МГУА 142.24207734573667 Лин.регрессия 132.94457227306145 Истинное значение 135.21
МГУА 117.10504949590465 Лин.регрессия 121.4072201678831 Истинное значение 117.709
МГУА 103.7047725181768 Лин.регрессия 115.13841173326152 Истинное значение 114.76
МГУА 128.84180036800876 Лин.регрессия 139.04756175590956 Истинное значение 141.551
МГУА 135.54193885687272 Лин.регрессия 142.46990115158985 Истинное значение 142.0
МГУА 142.24207734573667 Лин.регрессия 133.68649245966265 Истинное значение 136.0
МГУА 46.730578329648935 Лин.регрессия 48.06962088458796 Истинное значение 49.741
МГУА 78.56774466834482 Лин.регрессия 79.7113266427426 Истинное значение 80.5
МГУА -10.243615858878954 Лин.регрессия -11.062526470873124 Истинное значение -11.73
МГУА 97.0046340293129 Лин.регрессия 102.35273654821263 Истинное значение 106.47
МГУА 46.730578329648935 Ли

In [31]:
mean_err = 0
mean_sq_err = 0

In [33]:
mean_err = (predict_MGUA - y_test).sum() / predict_MGUA.shape[0]
mean_err = abs(mean_err)

In [34]:
mean_sq_err = ((predict_MGUA - y_test)**2).sum() / predict_MGUA.shape[0]

In [35]:
print("Средняя ошибка", mean_err)
print("Среднеквадратическая ошибка", mean_sq_err)

Средняя ошибка 1.446491687005105
Среднеквадратическая ошибка 56.74750037739382
