In [462]:
import numpy as np
from sklearn.linear_model import LinearRegression
import io
import seaborn as sns
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [463]:
data = np.loadtxt("alkan/ALKAN.BLD")


In [464]:
data

array([[ 2.,  1.,  0., ...,  2.,  1.,  1.],
       [ 2.,  0.,  2., ...,  5.,  2.,  1.],
       [ 2.,  0.,  2., ..., 10.,  4.,  2.],
       ...,
       [ 6.,  0.,  0., ..., 31., 13.,  2.],
       [ 6.,  0.,  0., ..., 32., 14.,  2.],
       [ 6.,  0.,  0., ..., 30., 12.,  2.]])

In [465]:
data.shape

(74, 210)

In [466]:
n = data.shape[0]
m = data.shape[1]

In [467]:
(n,m)

(74, 210)

In [468]:
l = []
word = 'A1 '
with io.open('alkan/set-str/ALKAN.SET') as file:
    for line in file:
        if (word in line):
            ape = float(line.split()[1])
            l.append(ape)

In [469]:
print("Num_features =", len(l))
for i in range(min(len(l), 10)):
    print("feature", i,"=", l[i])

Num_features = 74
feature 0 = -88.63
feature 1 = -42.07
feature 2 = -0.5
feature 3 = -11.73
feature 4 = 36.074
feature 5 = 27.852
feature 6 = 9.503
feature 7 = 68.74
feature 8 = 60.271
feature 9 = 63.282


In [470]:
y = np.array(l)
y.shape

(74,)

In [471]:
y

array([-88.63 , -42.07 ,  -0.5  , -11.73 ,  36.074,  27.852,   9.503,
        68.74 ,  60.271,  63.282,  49.741,  57.988,  98.427,  90.052,
        91.85 ,  93.475,  79.197,  89.784,  80.5  ,  86.064,  80.882,
       125.665, 117.647, 118.925, 117.709, 118.534, 106.84 , 115.607,
       109.429, 109.103, 111.969, 117.725, 115.65 , 118.259, 109.841,
        99.238, 114.76 , 113.467, 106.47 , 150.798, 143.26 , 144.18 ,
       142.48 , 143.   , 141.2  , 132.69 , 140.5  , 133.5  , 136.   ,
       135.21 , 137.3  , 140.6  , 136.   , 135.2  , 138.   , 133.8  ,
       140.6  , 140.4  , 133.6  , 126.54 , 124.084, 137.68 , 139.   ,
       131.34 , 130.648, 140.46 , 146.168, 133.83 , 142.   , 136.73 ,
       140.274, 133.016, 122.284, 141.551])

In [472]:
def R_rise_2 (Eps, y, y_mean):
    result1 = np.sum(Eps**2)
    result2 = np.sum((y-y_mean)**2)
    return 1 - result1 / result2

def Correlation(X, Y):
    X_mean = X.sum() / X.shape[0]
    Y_mean = Y.sum() / Y.shape[0]
    res = ((X - X_mean) * (Y - Y_mean)).sum()
    res1 = (((X - X_mean) ** 2)) 
    res2 = (((Y - Y_mean) ** 2)) 
    
    return  res / (((res1.sum() * res2.sum())) ** 0.5)

In [473]:
size_buf = 10
num_selections = 20
min_correlation = 0.95
#100
#15

In [474]:
model = LinearRegression()

In [475]:
y_mean = data.sum(axis = 1)
y_mean = y_mean / m
y_mean

array([0.09285714, 0.1907381 , 0.33778095, 0.31322381, 0.53822857,
       0.50626667, 0.46634762, 0.79669048, 0.74421905, 0.74644286,
       0.7040619 , 0.69749048, 1.11633333, 1.06962381, 1.06011905,
       1.02632381, 0.99708095, 0.99303333, 1.00302857, 0.9837381 ,
       0.93640952, 1.494     , 1.42669524, 1.41860952, 1.43021905,
       1.40549524, 1.36054762, 1.37269524, 1.3561    , 1.37696667,
       1.35222857, 1.3351619 , 1.32382381, 1.3034619 , 1.2579381 ,
       1.27928095, 1.27077619, 1.29133333, 1.18765238, 1.95123333,
       1.87832857, 1.85914286, 1.87329524, 1.82781905, 1.83665714,
       1.78150476, 1.79542857, 1.79074286, 1.78900476, 1.79551905,
       1.7769    , 1.77144762, 1.76990952, 1.77332857, 1.76851429,
       1.76265714, 1.73765238, 1.7309    , 1.70322857, 1.6973619 ,
       1.72905238, 1.70461429, 1.6983381 , 1.73022857, 1.69916667,
       1.66721429, 1.67419048, 1.63922857, 1.64113333, 1.67244286,
       1.5761619 , 1.60750476, 1.60711429, 1.60879524])

In [476]:
buf_r = np.array([0.0 for i in range(size_buf)])

iter_buf = 0

buf_numbers = np.array([[-1 for i in range(size_buf)] for k in range(num_selections)])
buf_numbers_1 = np.array([[-1 for i in range(size_buf)] for k in range(num_selections)])

buf = np.array([[[float(i) for i in range(size_buf)] for j in range(n)] for k in range(num_selections)])

X1 = np.array([[float(i) for i in range(1)] for j in range(n)])
X2 = np.array([[float(i) for i in range(2)] for j in range(n)])
buf.shape

(20, 74, 10)

In [518]:
%%time
for i in range(m):
    X1[:,0] = data[:,i]
    model.fit(X1, y)
    if iter_buf < size_buf:
            tmp = model.predict(X1)
            buf_r[iter_buf] = R_rise_2(y - tmp, y, y_mean)
            buf_numbers[0, iter_buf] = i
            buf[0, :, iter_buf] = tmp[:]
            iter_buf += 1
            
    else:
            tmp = model.predict(X1)
            ind = buf_r.argmin()
            ar = np.array([])
            for j in range (buf.shape[2]):
                t = Correlation (buf[0, :,j], tmp)
                ar = np.append (ar, t)
                
            if ar.max() < min_correlation: 
                buf_r[ind] = R_rise_2(y - tmp, y, y_mean)
                buf_numbers[0, ind] = i
                buf[0, :, ind] = tmp[:]
buf_numbers_1[0, :] = -2
print(buf_numbers, end="\n\n\n\n")

[[205 209 190 201 188 192 203 191 193 194]
 [  1   2   3   4   9   6   9   8   9  10]
 [  9   2   3   4   5   6   7   8   9  10]
 [  9   9   3   9   5   9   7   9   9   9]
 [  1   9   3   9   5   9   7   9   9   9]
 [  9   9   3   9   5   9   9   9   9   9]
 [  1   2   3   9   5   9   7   9   9   9]
 [  9   2   3   4   5   6   7   8   9  10]
 [  1   2   3   4   5   6   7   8   9  10]
 [  9   2   3   4   5   6   7   8   9  10]
 [  1   2   3   9   5   9   7   9   9   9]
 [  9   2   3   4   5   6   7   8   9  10]
 [  1   2   3   4   5   9   7   9   9   9]
 [  9   2   3   4   5   6   7   8   9  10]
 [  1   2   3   9   5   9   7   9   9   9]
 [  9   2   3   4   5   6   7   8   9  10]
 [  1   2   3   9   5   9   7   8   9   9]
 [  9   2   3   4   5   6   7   8   9  10]
 [  1   2   3   9   5   9   7   9   9   9]
 [  9   2   3   4   5   6   7   8   9  10]]



CPU times: user 571 ms, sys: 15.9 ms, total: 587 ms
Wall time: 147 ms


In [526]:
%%time
for k in range (1, num_selections):
    iter_buf = 0
    for i in range(size_buf):
        for j in range(i + 1, m):
            #print(data[:,i].shape)
            X2[:, 0] = buf[k - 1, :, i]
            X2[:, 1] = data[:, j]
            model.fit(X2, y)
            if iter_buf < size_buf:
                tmp = model.predict(X2)
                buf_r[iter_buf] = R_rise_2(y - tmp, y, y_mean)
                buf_numbers[k, iter_buf] = j
                buf_numbers_1[k, iter_buf] = i
                buf[k, :,iter_buf] = tmp[:]
                iter_buf += 1

            else:
                tmp = model.predict(X2)
                ind = buf_r.argmin()
                ar = np.array([])
                for j in range (buf.shape[2]):
                    t = Correlation (buf[0, :,j], tmp)
                    ar = np.append (ar, t)
                if ar.max() < min_correlation:
                    buf_r[ind] = R_rise_2(y - tmp, y, y_mean)
                    buf_numbers[k, ind] = j
                    buf_numbers_1[k, ind] = i
                    buf[k, :, ind] = tmp[:]

    print("selection", k + 1, "from", num_selections)

selection 2 from 20
selection 3 from 20
selection 4 from 20
selection 5 from 20
selection 6 from 20
selection 7 from 20
selection 8 from 20
selection 9 from 20
selection 10 from 20
selection 11 from 20
selection 12 from 20
selection 13 from 20
selection 14 from 20
selection 15 from 20
selection 16 from 20
selection 17 from 20
selection 18 from 20
selection 19 from 20
selection 20 from 20
CPU times: user 1min 52s, sys: 1.62 s, total: 1min 54s
Wall time: 28.6 s


In [527]:
buf_numbers

array([[205, 209, 190, 201, 188, 192, 203, 191, 193, 194],
       [  9,   9,   9,   9,   9,   9,   9,   9,   9,   9],
       [  9,   9,   9,   9,   9,   9,   9,   9,   9,   9],
       [  1,   2,   9,   4,   9,   6,   9,   8,   9,   9],
       [  9,   2,   3,   4,   5,   6,   9,   8,   9,  10],
       [  9,   2,   3,   4,   5,   6,   9,   8,   9,  10],
       [  9,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  9,   9,   9,   9,   9,   9,   9,   9,   9,   9],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  9,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  9,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  9,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  9,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10

In [528]:
buf_numbers_1

array([[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [ 8,  8,  7,  1,  0,  7,  9,  0,  9,  1],
       [ 5,  4,  5,  5,  5,  7,  7,  9,  7,  7],
       [ 0,  0,  9,  0,  0,  0,  5,  0,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 6,  0,  0,  0,  0,  0,  0,  0,  8,  0],
       [ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [529]:
lis = []
for i in range(size_buf):
    lis.append([buf_numbers[num_selections - 1][i]])


In [530]:
for i in range(num_selections - 1, 1, -1):
    #print(i)
    for j in range(size_buf):
        lis[j].append(buf_numbers[i - 1][buf_numbers_1[i,j]])



In [531]:
for i in range(size_buf):
    lis[i].append(buf_numbers[0][i])

In [532]:
for i in range(size_buf):
    lis[i].sort()

In [570]:
clf = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(data, y, train_size=0.8)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

/home/evgeny/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


-11.695700505282568

In [571]:
for i in range(size_buf):
    clf.fit(X_train[:,lis[i]], y_train)
    print(clf.score(X_test[:,lis[i]], y_test))

0.5797094614020484
-3.2431878437717973e+27
0.662278591328651
0.7713625270893886
0.9626287295408718
0.3737828790037769
0.7545498758863751
0.6363608146440234
0.1256069490882218
0.6835617389662618


In [572]:
X1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
Y1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [573]:
Correlation(Y1, X1)

1.0

In [574]:
0.25 **2


0.0625

In [575]:
clf.fit(data[1:-1,:], y[1:-1])
data[0:2,:].shape

(2, 210)

In [576]:
clf = LinearRegression ()
def cross_validation(clf, data, y):
    for i in range (data.shape[0]):
        d = data[i:i+1,:]
        y_1 = y[i]
        clf.fit (np.delete(data, i, axis=0), np.delete(y, i))
        print(R_rise_2 (y_1 - clf.predict(d), y_1, (d.sum() / d.shape[1])))
        
cross_validation (clf, data, y)

-2.651726441355756
-39.96560310026973
-18423.86993295176
0.9134557932152902
-43.69606733739315
0.9994579624956441
0.8156051956654364
-1.406848738808006
0.9999445324841069
0.9999689423848356
0.9998751271481379
0.9998701332917312
0.5825827907434362
0.9977105666730196
0.9999873382957977
0.9999531862238537
0.9999334218933181
0.955868117766478
0.9978057151498546
0.9999835878738415
0.9998490369139087
0.8866828361079586
0.9336025594736956
0.9996717890733723
0.9998832378717538
0.9998966385954328
-0.3213013036467758
0.9975232130467943
0.9997031749360293
-4.492466504634677
0.9999916815559626
0.9999065678702453
0.9999283901295183
0.9999603933961473
0.9999072352163961
-15.456879453963623
0.9999334243092255
0.9999443227886755
0.8623691479707363
0.6706751099510859
0.98281745616178
0.7737502004358175
0.9999947501934973
0.9990904266019411
0.9999187158567859
-2.0266078180713047
0.6517301141692005
0.5223239903476746
0.7140931705694042
-5.567839910274166
0.8614851473334127
0.9578957662586036
0.7109147670

In [577]:

cross_validation (clf, data[:,lis[0]], y)

-0.5677518220476316
-4.153137979910047
-12384.488435656196
-27.00719805391775
-1.5193167305429087
-1.3792787101408677
-16.581328351289503
0.5301739286308355
0.7114414112741607
0.7857530297992807
0.8394409129737334
0.9621088492020808
0.825981170653387
0.9201103929320147
0.9338564698145776
0.9997106071145954
0.973038015778139
0.999409631569806
0.9789774391643973
0.9951663374265125
0.9754476217335999
0.9081766160106243
0.9674772779624763
0.9720057137114998
0.9677071513853109
0.9991165034195948
0.9938646617197099
0.9999775918088583
0.9972530715020634
0.9969078910305134
0.9992074789824096
0.9994737025097786
0.9560732178052667
0.9482491205090653
0.9722211188654968
0.9943219018509414
0.9586714930645337
0.9623735595572008
0.8628657072604752
0.9365383497494936
0.9818371019606126
0.9838443941094615
0.9800212542325732
0.9988120167400862
0.9995262559328253
0.9981543955808707
0.9997198352382681
0.9986718652530803
0.999717078619639
0.999473635414206
0.9999524013611508
0.9996951688471764
0.9997170786

In [ ]:
ara = np.array([])
