In [440]:
import numpy as np
from sklearn.linear_model import LinearRegression
import io
import seaborn as sns
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [441]:
data = np.loadtxt("alkan/ALKAN.BLD")


In [442]:
data

array([[ 2.,  1.,  0., ...,  2.,  1.,  1.],
       [ 2.,  0.,  2., ...,  5.,  2.,  1.],
       [ 2.,  0.,  2., ..., 10.,  4.,  2.],
       ...,
       [ 6.,  0.,  0., ..., 31., 13.,  2.],
       [ 6.,  0.,  0., ..., 32., 14.,  2.],
       [ 6.,  0.,  0., ..., 30., 12.,  2.]])

In [443]:
data.shape

(74, 210)

In [444]:
n = data.shape[0]
m = data.shape[1]

In [445]:
(n,m)

(74, 210)

In [446]:
l = []
word = 'A1 '
with open('alkan/set-str/ALKAN.SET') as file:
    for line in file:
        if (word in line):
            ape = float(line.split()[1])
            l.append(ape)

In [447]:
print("Num_features =", len(l))
for i in range(min(len(l), 10)):
    print("feature", i,"=", l[i])

Num_features = 74
feature 0 = -88.63
feature 1 = -42.07
feature 2 = -0.5
feature 3 = -11.73
feature 4 = 36.074
feature 5 = 27.852
feature 6 = 9.503
feature 7 = 68.74
feature 8 = 60.271
feature 9 = 63.282


In [448]:
y = np.array(l)
y.shape

(74,)

In [449]:
y

array([-88.63 , -42.07 ,  -0.5  , -11.73 ,  36.074,  27.852,   9.503,
        68.74 ,  60.271,  63.282,  49.741,  57.988,  98.427,  90.052,
        91.85 ,  93.475,  79.197,  89.784,  80.5  ,  86.064,  80.882,
       125.665, 117.647, 118.925, 117.709, 118.534, 106.84 , 115.607,
       109.429, 109.103, 111.969, 117.725, 115.65 , 118.259, 109.841,
        99.238, 114.76 , 113.467, 106.47 , 150.798, 143.26 , 144.18 ,
       142.48 , 143.   , 141.2  , 132.69 , 140.5  , 133.5  , 136.   ,
       135.21 , 137.3  , 140.6  , 136.   , 135.2  , 138.   , 133.8  ,
       140.6  , 140.4  , 133.6  , 126.54 , 124.084, 137.68 , 139.   ,
       131.34 , 130.648, 140.46 , 146.168, 133.83 , 142.   , 136.73 ,
       140.274, 133.016, 122.284, 141.551])

In [450]:
def R_rise_2 (Eps, y, y_mean):
    result1 = np.sum(Eps**2)
    result2 = np.sum((y-y.mean())**2)
    return 1 - result1 / result2


def Correlation(X, Y):
    X_mean = X.sum() / X.shape[0]
    Y_mean = Y.sum() / Y.shape[0]
    res = ((X - X_mean) * (Y - Y_mean)).sum()
    res1 = (((X - X_mean) ** 2)) 
    res2 = (((Y - Y_mean) ** 2)) 
    
    return  res / (((res1.sum() * res2.sum())) ** 0.5)

In [451]:
size_buf = 10
num_selections = 10
min_correlation = 0.95
#100
#15

In [452]:
model = LinearRegression()

In [453]:
y_mean = data.sum(axis = 1)
y_mean = y_mean / m
y_mean

array([0.09285714, 0.1907381 , 0.33778095, 0.31322381, 0.53822857,
       0.50626667, 0.46634762, 0.79669048, 0.74421905, 0.74644286,
       0.7040619 , 0.69749048, 1.11633333, 1.06962381, 1.06011905,
       1.02632381, 0.99708095, 0.99303333, 1.00302857, 0.9837381 ,
       0.93640952, 1.494     , 1.42669524, 1.41860952, 1.43021905,
       1.40549524, 1.36054762, 1.37269524, 1.3561    , 1.37696667,
       1.35222857, 1.3351619 , 1.32382381, 1.3034619 , 1.2579381 ,
       1.27928095, 1.27077619, 1.29133333, 1.18765238, 1.95123333,
       1.87832857, 1.85914286, 1.87329524, 1.82781905, 1.83665714,
       1.78150476, 1.79542857, 1.79074286, 1.78900476, 1.79551905,
       1.7769    , 1.77144762, 1.76990952, 1.77332857, 1.76851429,
       1.76265714, 1.73765238, 1.7309    , 1.70322857, 1.6973619 ,
       1.72905238, 1.70461429, 1.6983381 , 1.73022857, 1.69916667,
       1.66721429, 1.67419048, 1.63922857, 1.64113333, 1.67244286,
       1.5761619 , 1.60750476, 1.60711429, 1.60879524])

In [454]:
buf_r = np.array([0.0 for i in range(size_buf)])

iter_buf = 0

buf_numbers = np.array([[-1 for i in range(size_buf)] for k in range(num_selections)])
buf_numbers_1 = np.array([[-1 for i in range(size_buf)] for k in range(num_selections)])

buf = np.array([[[float(i) for i in range(size_buf)] for j in range(n)] for k in range(num_selections)])

X1 = np.array([[float(i) for i in range(1)] for j in range(n)])
X2 = np.array([[float(i) for i in range(2)] for j in range(n)])
buf.shape

(10, 74, 10)

In [455]:
%%time
for i in range(m):
    X1[:,0] = data[:,i]
    model.fit(X1, y)
    if iter_buf < size_buf:
            tmp = model.predict(X1)
            buf_r[iter_buf] = R_rise_2(y - tmp, y, y_mean)
            buf_numbers[0, iter_buf] = i
            buf[0, :, iter_buf] = tmp[:]
            iter_buf += 1
            
    else:
            tmp = model.predict(X1)
            ind = buf_r.argmin()
            ar = np.array([])
            for j in range (buf.shape[2]):
                t = Correlation (buf[0, :,j], tmp)
                ar = np.append (ar, t)
                
            if (ar.max() < min_correlation) and (buf_r[ind] < R_rise_2(y - tmp, y, y_mean)): 
                buf_r[ind] = R_rise_2(y - tmp, y, y_mean)
                buf_numbers[0, ind] = i
                buf[0, :, ind] = tmp[:]
buf_numbers_1[0, :] = -2
print(buf_numbers, end="\n\n\n\n")

[[205 209 190 201 188 192 203 191 193 194]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]]



CPU times: user 642 ms, sys: 3.84 ms, total: 646 ms
Wall time: 163 ms


In [456]:
%%time
for k in range (1, num_selections):
    iter_buf = 0
    for i in range(size_buf):
        for j in range(i + 1, m):
            #print(data[:,i].shape)
            X2[:, 0] = buf[k - 1, :, i]
            X2[:, 1] = data[:, j]
            model.fit(X2, y)
            if iter_buf < size_buf:
                tmp = model.predict(X2)
                buf_r[iter_buf] = R_rise_2(y - tmp, y, y_mean)
                buf_numbers[k, iter_buf] = j
                buf_numbers_1[k, iter_buf] = i
                buf[k, :,iter_buf] = tmp[:]
                iter_buf += 1

            else:
                tmp = model.predict(X2)
                ind = buf_r.argmin()
                ar = np.array([])
                for j in range (buf.shape[2]):
                    t = Correlation (buf[0, :,j], tmp)
                    ar = np.append (ar, t)
                if (ar.max() < min_correlation) and (buf_r[ind] < R_rise_2(y - tmp, y, y_mean)):
                    buf_r[ind] = R_rise_2(y - tmp, y, y_mean)
                    buf_numbers[k, ind] = j
                    buf_numbers_1[k, ind] = i
                    buf[k, :, ind] = tmp[:]

    print("selection", k + 1, "from", num_selections)

selection 2 from 10
selection 3 from 10
selection 4 from 10
selection 5 from 10
selection 6 from 10
selection 7 from 10
selection 8 from 10
selection 9 from 10
selection 10 from 10
CPU times: user 55.5 s, sys: 756 ms, total: 56.3 s
Wall time: 14.1 s


In [457]:
buf_numbers

array([[205, 209, 190, 201, 188, 192, 203, 191, 193, 194],
       [  9,   9,   9,   9,   9,   9,   9,   9,   9,   9],
       [  9,   9,   9,   9,   9,   9,   9,   9,   9,   9],
       [  1,   2,   3,   4,   9,   6,   9,   8,   9,   9],
       [  9,   2,   3,   4,   5,   6,   9,   8,   9,  10],
       [  9,   2,   3,   4,   5,   6,   9,   8,   9,  10],
       [  9,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [458]:
buf_numbers_1

array([[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [ 8,  8,  7,  1,  0,  7,  9,  0,  2,  1],
       [ 5,  4,  5,  5,  5,  7,  7,  5,  7,  7],
       [ 0,  0,  0,  0,  0,  0,  5,  0,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [459]:
lis = []
for i in range(size_buf):
    lis.append([buf_numbers[num_selections - 1][i]])


In [460]:
for i in range(num_selections - 1, 1, -1):
    #print(i)
    for j in range(size_buf):
        lis[j].append(buf_numbers[i - 1][buf_numbers_1[i,j]])



In [461]:
for i in range(size_buf):
    lis[i].append(buf_numbers[0][i])

In [462]:
for i in range(size_buf):
    lis[i].sort()
    print(lis[i])

[1, 1, 1, 1, 9, 9, 9, 9, 9, 205]
[1, 1, 1, 2, 9, 9, 9, 9, 9, 209]
[1, 1, 1, 3, 9, 9, 9, 9, 9, 190]
[1, 1, 1, 4, 9, 9, 9, 9, 9, 201]
[1, 1, 1, 5, 9, 9, 9, 9, 9, 188]
[1, 1, 1, 6, 9, 9, 9, 9, 9, 192]
[1, 1, 1, 7, 9, 9, 9, 9, 9, 203]
[1, 1, 1, 8, 9, 9, 9, 9, 9, 191]
[1, 1, 1, 9, 9, 9, 9, 9, 9, 193]
[1, 1, 1, 9, 9, 9, 9, 9, 10, 194]


In [490]:
clf = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(data, y, train_size=0.8)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

/home/evgeny/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


-23.490917650049887

In [491]:
for i in range(size_buf):
    clf.fit(X_train[:,np.unique(lis[i])], y_train)
    print(clf.score(X_test[:,np.unique(lis[i])], y_test))

-0.267549596598476
-0.39420986385486056
0.1310638944407816
0.4988112606781413
0.8977564893602197
-0.16435131778328627
0.8053959708674858
0.2584721483019087
-0.3538475229365876
-0.25781783619116494


In [477]:
X1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
Y1 = np.array([1,2,3,4,5,6,7123,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [478]:
Correlation(Y1, X1)

-0.13560132351873908

In [479]:
0.25 **2


0.0625

In [480]:
clf.fit(data[1:-1,:], y[1:-1])
data[0:2,:].shape

(2, 210)

In [483]:
clf = LinearRegression ()
#print(y.shape)
def cross_validation(clf, data, y):
    lis = []
    for i in range (data.shape[0]):
        d = data[i:i+1,:]
        y_1 = y[i]
        clf.fit (data, y)
        print(clf.score(d, y_1))
        lis.append(clf.score(d, y_1))
    return np.array(lis)
        
a1 = cross_validation (clf, data, y)

TypeError: Singleton array -88.63 cannot be considered a valid collection.

In [430]:

a2 = cross_validation (clf, data[:,np.unique(lis[3])], y)

In [431]:
for i in range(a1.shape[0]):
    print(a1[i], a2[i])


1.0 1.0
1.0 64.49657388177383
1.0 443.78294602128733
1.0000013844538134 94.75149058375693
1.0 0.9395955776940229
0.9999819434353143 -9.544074000363903
0.999998575457407 -41.254701639165845
1.0 1.0
0.9999827920913773 0.9806475110330823
0.9999734785262838 0.3481676606577553
0.9999863519448567 0.8404553808191191
0.9999917529492334 0.8296123709594343
1.0 -0.5455277361761743
0.9999998751263982 0.99888676662055
0.9999787355681794 0.4869508636605152
0.9999945495864068 0.35877194805161416
0.9999936781058216 -1.1783304296755772
0.9999999934745415 0.7918317834089457
0.9999998173961425 -1.0476691773950613
0.9999800631752885 0.16419270869035363
0.9999973879088723 -0.5446601806296238
1.0 0.8338886539985713
1.0 -0.0826506696739131
0.999999621774476 0.9989503823003075
0.9999989030485973 -0.6665172535444066
0.9999987872439234 0.995326296234427
1.0 0.8156635475984607
0.9999999454450539 -0.010902054385597104
0.9999994626795267 0.3322271736550283
1.0 -2.1467416017211214
0.9999821137974537 -2.299683433406