In [240]:
import numpy as np
from sklearn.linear_model import LinearRegression
import io

In [241]:
data = np.loadtxt("alkan/ALKAN.BLD")


In [242]:
data

array([[ 2.,  1.,  0., ...,  2.,  1.,  1.],
       [ 2.,  0.,  2., ...,  5.,  2.,  1.],
       [ 2.,  0.,  2., ..., 10.,  4.,  2.],
       ...,
       [ 6.,  0.,  0., ..., 31., 13.,  2.],
       [ 6.,  0.,  0., ..., 32., 14.,  2.],
       [ 6.,  0.,  0., ..., 30., 12.,  2.]])

In [243]:
data.shape

(74, 210)

In [244]:
n = data.shape[0]
m = data.shape[1]

In [245]:
(n,m)

(74, 210)

In [246]:
l = []
word = 'A1 '
with io.open('alkan/set-str/ALKAN.SET') as file:
    for line in file:
        if (word in line):
            ape = float(line.split()[1])
            #print(ape)
            l.append(ape)

In [247]:
print("Num_features =", len(l))
for i in range(min(len(l), 10)):
    print("feature", i,"=", l[i])

Num_features = 74
feature 0 = -88.63
feature 1 = -42.07
feature 2 = -0.5
feature 3 = -11.73
feature 4 = 36.074
feature 5 = 27.852
feature 6 = 9.503
feature 7 = 68.74
feature 8 = 60.271
feature 9 = 63.282


In [248]:
y = np.array(l)
y.shape

(74,)

In [249]:
y

array([-88.63 , -42.07 ,  -0.5  , -11.73 ,  36.074,  27.852,   9.503,
        68.74 ,  60.271,  63.282,  49.741,  57.988,  98.427,  90.052,
        91.85 ,  93.475,  79.197,  89.784,  80.5  ,  86.064,  80.882,
       125.665, 117.647, 118.925, 117.709, 118.534, 106.84 , 115.607,
       109.429, 109.103, 111.969, 117.725, 115.65 , 118.259, 109.841,
        99.238, 114.76 , 113.467, 106.47 , 150.798, 143.26 , 144.18 ,
       142.48 , 143.   , 141.2  , 132.69 , 140.5  , 133.5  , 136.   ,
       135.21 , 137.3  , 140.6  , 136.   , 135.2  , 138.   , 133.8  ,
       140.6  , 140.4  , 133.6  , 126.54 , 124.084, 137.68 , 139.   ,
       131.34 , 130.648, 140.46 , 146.168, 133.83 , 142.   , 136.73 ,
       140.274, 133.016, 122.284, 141.551])

In [250]:
def R_rise_2 (Eps, y, y_mean):
    result1 = np.sum(Eps**2)
    result2 = np.sum((y-y_mean)**2)
    return 1 - result1 / result2

In [251]:
size_buf = 10
num_selections = 15

In [252]:
model = LinearRegression()

In [253]:
y_mean = data.sum(axis = 1)
y_mean = y_mean / m
y_mean

array([0.09285714, 0.1907381 , 0.33778095, 0.31322381, 0.53822857,
       0.50626667, 0.46634762, 0.79669048, 0.74421905, 0.74644286,
       0.7040619 , 0.69749048, 1.11633333, 1.06962381, 1.06011905,
       1.02632381, 0.99708095, 0.99303333, 1.00302857, 0.9837381 ,
       0.93640952, 1.494     , 1.42669524, 1.41860952, 1.43021905,
       1.40549524, 1.36054762, 1.37269524, 1.3561    , 1.37696667,
       1.35222857, 1.3351619 , 1.32382381, 1.3034619 , 1.2579381 ,
       1.27928095, 1.27077619, 1.29133333, 1.18765238, 1.95123333,
       1.87832857, 1.85914286, 1.87329524, 1.82781905, 1.83665714,
       1.78150476, 1.79542857, 1.79074286, 1.78900476, 1.79551905,
       1.7769    , 1.77144762, 1.76990952, 1.77332857, 1.76851429,
       1.76265714, 1.73765238, 1.7309    , 1.70322857, 1.6973619 ,
       1.72905238, 1.70461429, 1.6983381 , 1.73022857, 1.69916667,
       1.66721429, 1.67419048, 1.63922857, 1.64113333, 1.67244286,
       1.5761619 , 1.60750476, 1.60711429, 1.60879524])

In [318]:
buf_r = np.array([0.0 for i in range(size_buf)])

iter_buf = 0

buf_numbers = np.array([[-1 for i in range(size_buf)] for k in range(num_selections)])
buf_numbers_1 = np.array([[-1 for i in range(size_buf)] for k in range(num_selections)])

buf = np.array([[[float(i) for i in range(size_buf)] for j in range(n)] for k in range(num_selections)])

X1 = np.array([[float(i) for i in range(1)] for j in range(n)])
X2 = np.array([[float(i) for i in range(2)] for j in range(n)])
buf.shape

(15, 74, 10)

In [319]:
%%time
for i in range(m):
    X1[:,0] = data[:,i]
    model.fit(X1, y)
    if iter_buf < size_buf:
            tmp = model.predict(X1)
            buf_r[iter_buf] = R_rise_2(y - tmp, y, y_mean)
            buf_numbers[0, iter_buf] = i
            buf[0, :, iter_buf] = tmp[:]
            iter_buf+= 1
            
    else:
            tmp = model.predict(X1)
            ind = buf_r.argmin()
            buf_r[ind] = R_rise_2(y - tmp, y, y_mean)
            buf_numbers[0, ind] = i
            buf[0, :, ind] = tmp[:]
buf_numbers_1[0, :] = -2
print(buf_numbers_1, end="\n\n\n\n")

[[ 0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]



CPU times: user 297 ms, sys: 8.04 ms, total: 305 ms
Wall time: 76.2 ms


In [326]:
%%time
for k in range (1, num_selections):
    iter_buf = 0
    for i in range(size_buf):
        for j in range(i + 1, m):
            #print(data[:,i].shape)
            X2[:, 0] = buf[k - 1, :, i]
            X2[:, 1] = data[:, j]
            model.fit(X2, y)
            if iter_buf < size_buf:
                tmp = model.predict(X2)
                buf_r[iter_buf] = R_rise_2(y - tmp, y, y_mean)
                buf_numbers[k, iter_buf] = j
                buf_numbers_1[k, iter_buf] = i
                buf[k, :,iter_buf] = tmp[:]
                iter_buf += 1

            else:
                tmp = model.predict(X2)
                ind = buf_r.argmin()
                buf_r[ind] = R_rise_2(y - tmp, y, y_mean)
                buf_numbers[k, ind] = j
                buf_numbers_1[k, ind] = i
                buf[k, :, ind] = tmp[:]

CPU times: user 39.7 s, sys: 538 ms, total: 40.2 s
Wall time: 10.1 s


In [321]:
buf_numbers

array([[196, 201, 189, 202, 188, 208, 195, 209, 203, 206],
       [196, 196, 209, 193, 196, 188, 197, 201, 189, 197],
       [206, 206, 192, 192, 206, 206, 206, 199, 209, 206],
       [131, 209, 133,   6,   6, 132, 132, 133, 131, 132],
       [192, 192, 199, 199, 192, 192, 199, 209, 199, 192],
       [  1, 200, 193, 193, 200, 200, 193, 200, 209, 193],
       [121, 186, 121, 122, 186, 209, 122, 121, 186, 186],
       [  1, 113, 113, 113, 113, 113, 113, 209, 112, 112],
       [209, 129,  73, 172, 112, 129, 113,  73,  72, 172],
       [ 73, 209,  73,  72, 172, 132, 172, 129, 129,  72],
       [132, 172, 129,  73, 132, 209, 132, 132, 208,  72],
       [110, 111, 115, 153, 184, 209, 111, 111, 184, 110],
       [115, 153, 153, 115, 110, 209, 184, 153, 115, 111],
       [ 86,  86,  86,  86,  86, 177, 177, 177, 209,  86],
       [  5, 147, 147,   5, 147,   5, 209, 147, 147, 147]])

In [323]:
buf_numbers_1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 9, 0, 4, 0, 4, 0, 0, 2],
       [8, 5, 9, 6, 9, 6, 4, 3, 9, 1],
       [4, 9, 4, 4, 5, 4, 5, 5, 5, 1],
       [5, 6, 5, 6, 0, 8, 8, 9, 0, 4],
       [0, 5, 6, 4, 6, 4, 8, 8, 9, 5],
       [7, 4, 4, 7, 7, 9, 4, 2, 6, 2],
       [0, 0, 2, 1, 4, 3, 6, 9, 0, 4],
       [9, 1, 2, 2, 0, 2, 0, 1, 2, 1],
       [6, 9, 4, 4, 4, 6, 6, 6, 4, 6],
       [9, 5, 5, 5, 0, 9, 7, 6, 7, 5],
       [8, 8, 8, 8, 8, 9, 6, 0, 6, 7],
       [4, 1, 4, 0, 2, 9, 2, 0, 1, 2],
       [8, 3, 4, 9, 6, 6, 4, 9, 9, 0],
       [4, 5, 7, 3, 4, 2, 9, 6, 2, 3]])

In [327]:
lis = []
for i in range(num_selections):
    lis


SyntaxError: invalid syntax (<ipython-input-327-e18b71ce101d>, line 1)